name: cat LICENSE
 on: push
 jobs:
   my-job:
     runs-on: ubuntu-latest
     steps:
       - name: checkout repo
         uses: actions/checkout@v3
       - name: cat LICENSE
         run: cat LICENSE
